name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Test plugin
    runs-on: ubuntu-latest

    steps:
      - name: Check out code onto host
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.0'
          cache: 'npm'

      - name: Output versions
        run: |
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"

      - name: Install node modules
        run: npm ci

      - name: Run unit tests
        run: npm run test
